/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Client;
import controlador.UserController;
import java.sql.Timestamp;
import javax.swing.DefaultListModel;

/**
 *
 * @author lolac
 */
public class MainUI extends javax.swing.JFrame {

    UserController user;
    DefaultListModel friend_model_list;
    
    Client cliente;
    
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }
    
    public void setUser(UserController user, Client cliente){
        
        this.user = user;
        
        this.cliente = cliente;
        
        this.cliente.CP.manageInfoOfUser(this.cliente.getAllInfoOfUser(this.user.getLogin()), this.user);
        
        this.completarInfoUsuario();
        
        this.friend_model_list = new DefaultListModel<>();
        
        this.agregarAmigosAModelo();
        
        this.friend_list.setModel(this.friend_model_list);
        
        this.friend_name.setText("");
        this.friend_status.setText("");
        
    }
    
    public void completarInfoUsuario(){
        
        if(this.user.getName() != ""){
            this.user_name.setText(this.user.getLogin());
            this.user_name_and_surnames.setText(this.user.getName() + " " + this.user.getSurname_1() + " " +  this.user.getSurname_2());
        }
    }

    
    public void agregarAmigosAModelo(){
        
        for(int index = 0; index < this.user.getFriendListSIze(); index++){
            
            this.friend_model_list.addElement(this.user.getFriend_list().get(index).getFriend_login() + ", " + this.user.getFriend_list().get(index).getFriend_state());
        }
    }
    
    public void setUser(UserController user){
        this.user = user;
    }
    
    public static void debugClient(String debug){
        System.out.println(debug + "\n");
        debug_area_client.append(debug + "\n");
    }
    
    public void thereAreNoMessages(){
System.out.println("Entramos en poner que no hay mensajes");
        this.chat.setText("There are no messages between these two friends");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        friend_list = new javax.swing.JList<>();
        user_name = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        chat = new javax.swing.JTextArea();
        friend_name = new javax.swing.JLabel();
        user_name_and_surnames = new javax.swing.JLabel();
        friend_status = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        debug_area_client = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        friend_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friend_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(friend_list);

        user_name.setText("Login");

        chat.setEditable(false);
        chat.setColumns(20);
        chat.setRows(5);
        jScrollPane3.setViewportView(chat);

        friend_name.setText("Nombre amigo");

        user_name_and_surnames.setText("Nombre usuario");

        friend_status.setText("Estado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_name)
                    .addComponent(user_name_and_surnames))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(friend_status)
                    .addComponent(friend_name))
                .addGap(137, 137, 137))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(friend_name)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(user_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user_name_and_surnames))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(friend_status)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Chats", jPanel1);

        debug_area_client.setColumns(20);
        debug_area_client.setRows(5);
        jScrollPane2.setViewportView(debug_area_client);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DEBUG", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void friend_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friend_listMouseClicked
        
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        
        this.friend_status.setText(this.cliente.askForStatusOfUser(this.user.getLogin(), this.user.getFriend_list().get(this.friend_list.getSelectedIndex()).getFriend_login()));
        this.friend_name.setText(this.user.getFriend_list().get(this.friend_list.getSelectedIndex()).getFriend_login());
System.out.println("Funsiona");
        
        this.cliente.sendMessagesRequest(this.user.getLogin(), this.user.getFriend_list().get(this.friend_list.getSelectedIndex()).getFriend_login(), timestamp);
        
        this.friend_name.setText(this.user.getFriend_list().get(this.friend_list.getSelectedIndex()).getFriend_login());
        
        this.chat.setText("");
        String cosa = this.user.allMessagesToString(this.user.getLogin(), this.user.getFriend_list().get(this.friend_list.getSelectedIndex()).getFriend_login());
        if(cosa != null){
            
            this.chat.setText(cosa);
        }else{
            this.thereAreNoMessages();
            System.out.println("ESTO DA UN ERROR COMO UN CASTILLO SHAVÁ");
        }
    }//GEN-LAST:event_friend_listMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MainUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chat;
    public static javax.swing.JTextArea debug_area_client;
    private javax.swing.JList<String> friend_list;
    private javax.swing.JLabel friend_name;
    private javax.swing.JLabel friend_status;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel user_name;
    private javax.swing.JLabel user_name_and_surnames;
    // End of variables declaration//GEN-END:variables
}
